name: "AI Python Test Generator"
description: "Prototype GitHub Action"

inputs:
  mode:
    required: true
    default: "local"
  provider:
    required: true
    default: "ollama"
  model:
    required: true
    default: "qwen2.5-coder:0.5b"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        cd "$GITHUB_ACTION_PATH"
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt


    - name: Run main script
      run: |
        cd "$GITHUB_ACTION_PATH"
        python src/main.py \
          --mode "${{ inputs.mode }}" \
          --provider "${{ inputs.provider }}" \
          --model "${{ inputs.model }}"

