name: "AI Python Test Generator"
description: "Generates Python unit tests from code changes in a pull request."

branding:
  icon: 'code'
  color: 'blue'

inputs:
  mode:
    description: "The mode to run the action in. Currently only 'local' is supported."
    required: true
    default: "local"
  provider:
    description: "The LLM provider to use. Currently only 'ollama' is supported."
    required: true
    default: "ollama"
  model:
    description: "The LLM model to use for generating tests."
    required: true
    default: "qwen2.5-coder:0.5b"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --mode=${{ inputs.mode }}
    - --provider=${{ inputs.provider }}
    - --model=${{ inputs.model }}
