name: "AI Python Test Generator"
description: "Prototype GitHub Action"

inputs:
  mode:
    description: "llm mode: local or cloud"
    required: true
    default: "local"

  provider:
    description: "llm provider (ollama, openai)"
    required: true
    default: "ollama"

  model:
    description: "model name"
    required: true
    default: "qwen2.5-coder:0.5b"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r "%GITHUB_ACTION_PATH%\requirements.txt"
      shell: cmd

    - name: Run main script
      run: |
        python ${{ github.action_path }}/src/main.py \
          --mode "${{ inputs.mode }}" \
          --provider "${{ inputs.provider }}" \
          --model "${{ inputs.model }}"
      shell: cmd
